apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
health:
  healthProbeBindAddress: :18081
metrics:
  bindAddress: 127.0.0.1:18080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: 91b4d327.vmware.com
