
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - elk.vmware.com
  resources:
  - svelks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.vmware.com
  resources:
  - svelks/finalizers
  verbs:
  - update
- apiGroups:
  - elk.vmware.com
  resources:
  - svelks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elk.vmware.com.vmware.com
  resources:
  - tkcelks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.vmware.com.vmware.com
  resources:
  - tkcelks/finalizers
  verbs:
  - update
- apiGroups:
  - elk.vmware.com.vmware.com
  resources:
  - tkcelks/status
  verbs:
  - get
  - patch
  - update
