# permissions for end users to view svelks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: svelk-viewer-role
rules:
- apiGroups:
  - elk.vmware.com
  resources:
  - svelks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elk.vmware.com
  resources:
  - svelks/status
  verbs:
  - get
