# permissions for end users to edit svelks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: svelk-editor-role
rules:
- apiGroups:
  - elk.vmware.com
  resources:
  - svelks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elk.vmware.com
  resources:
  - svelks/status
  verbs:
  - get
