# permissions for end users to view tkcelks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tkcelk-viewer-role
rules:
- apiGroups:
  - elk.vmware.com.vmware.com
  resources:
  - tkcelks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elk.vmware.com.vmware.com
  resources:
  - tkcelks/status
  verbs:
  - get
